# This file and its contents are licensed under the Apache License 2.0.
# Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
{{- /*
The purpose of this Secret is to have random passwords set for all
the users required by Patroni.
As the secrets need to be somewhat static, we create them using a pre-install hook.
This however means they will *never* be recreated during the lifetime of a Helm deployment,

We create 2 sets of secrets: 1 for the access node, and 1 for all the data nodes,
which ensures that if nodes are added to the deployment, they will have a default set of
credentials to use.

It would be great if we could support 1 set of secrets per node, however due to the
dependency on the pre-install hook (to create static secrets), this pattern would not
support adding nodes to the deployment.
*/ -}}
{{- if (index .Values.metadata.annotations "service.helm.timescale.com/passwords-generate") }}
{{- range $nodeType := list "data" "access" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "patroniUsersPrefix" $ }}-{{ $nodeType }}
  labels:
    {{- include "timescaledb.labels" $ | nindent 4 }}
    timescaledb-node-type: {{ $nodeType }}
    timescaledb-name: {{ include "timescaledb.fullname" $ }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- range $role := list "postgres" "standby" }}
  {{ $role | quote }}: {{ randAlphaNum 30 | b64enc | quote }}
{{- end }}
...

{{- end }}
{{- end }}
