---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
    timescaledb-node-type: access
    cluster-name: {{ include "timescaledb.fullname" . }}
    timescaledb-name: {{ include "timescaledb.fullname" . }}
    timescaledb-node-name: {{ include "accessNode" . }}
    role: master
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
...
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}-replica
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
    timescaledb-node-type: access
    cluster-name: {{ include "timescaledb.fullname" . }}
    timescaledb-name: {{ include "timescaledb.fullname" . }}
    timescaledb-node-name: {{ include "accessNode" . }}
    role: master
spec:
  type: LoadBalancer
  selector:
    timescaledb-name: {{ include "timescaledb.fullname" $ }}
    timescaledb-node-name: {{ include "accessNode" . }}
    role: replica
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
...