apiVersion: v1
kind: Service
metadata:
  name: {{ template "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
    timescaledb-node-type: access
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP