$schema: https://json-schema.org/draft-07/schema#
additionalProperties: false
components:
  schemas:
    # Even though we currently only reference '#/components/schemas/User' once,
    # we define it separately here, because:
    # - we may reuse the definition (global users, local users)
    # - to keep the general structure easier to read
    User:
      additionalProperties:
        additionalProperties: false
        properties:
          password:
            additionalProperties: false
            properties:
              value:
                minLength: 8
                type: string
              valueFrom:
                additionalProperties: false
                properties:
                  secretKeyRef:
                    additionalProperties: false
                    properties:
                      key:
                        minLength: 1
                        type: string
                      name:
                        minLength: 1
                        type: string
                    required:
                    - name
                    - key
                type: object
            type: object
          privileges:
            additionalProperties: false
            description: https://www.postgresql.org/docs/current/sql-createrole.html
            properties:
              createdb:
                type: boolean
              createrole:
                type: boolean
              login:
                type: boolean
              replication:
                type: boolean
              superuser:
                type: boolean
            type: object
        type: object
      examples:
        additionalCreateDBUser:
          devops:
            privileges:
            - createdb
        plainTextPassword:
          admin:
            password:
              value: verysecret
        referToSelfManagedSecret:
          admin:
            password:
              valueFrom:
                secretKeyRef:
                  key: admin
                  name: selfManagedSecret
      type: object
properties:
  fullnameOverride:
    maxLength: 40
    type: string
  metadata:
    properties:
      annotations:
        additionalProperties: true
        properties:
          service.helm.timescale.com/backup-enabled:
            type: boolean
          service.helm.timescale.com/backup-method:
            type: string
          service.helm.timescale.com/generate-certificates:
            type: boolean
          service.helm.timescale.com/generate-passwords:
            type: boolean
          service.helm.timescale.com/network-policy-enabled:
            type: boolean
          service.helm.timescale.com/rbac-create:
            type: boolean
          service.helm.timescale.com/serviceaccount-create:
            type: boolean
          service.helm.timescale.com/timescaledb-tune-enabled:
            type: boolean
        type: object
    type: object
  nameOverride:
    maxLength: 40
    type: string
  readinessProbe:
    type: object
  serviceAccount:
    type: object
  spec:
    additionalProperties: false
    properties:
      accessNode:
        minLength: 1
        type:
        - string
        - 'null'  # Not specifying an access node is only allowed if there is 1 node under the "nodes" key
      # These configurations are referred to by the nodes in the top-level nodes key.
      # No overloading (dataNode inherits default) for example is done, each configuration is self-contained,
      configurations:
        additionalProperties:
          properties:
            image:
              example: timescaledev/timescaledb-ha:pg11-ts1.6-postgis
              minLength: 3
              type: string
            postgresql:
              properties:
                # parameters are the parameters you can set for the PostgreSQL server
                # we may wish to restrict setting some parameters, but we also like
                # to expose as much as possible of the underlying PostgreSQL
                # https://www.postgresql.org/docs/current/config-setting.html
                parameters:
                  additionalProperties:
                    type: string
                  example:
                    work_mem: 24MB
                  type: object
                # The version mentioned here will be used to set the PATH inside the
                # container, as well as which Docker image to fetch (if the image is not explicitly set)
                version:
                  minLength: 2
                  type: string
                  example: "11"
              type: object
            replicas:
              minimum: 1
              type: integer
          type: object
        type: object
      databases:
        additionalProperties:
          additionalProperties:
            type: string
          properties:
            encoding:
              example: UTF8
              minLength: 3
              type: string
            locale:
              example: C
              minLength: 1
              type: string
          type: object
        type: object
      debug:
        additionalProperties: false
        properties:
          execStartPre:
            type:
            - string
            - 'null'
        type: object
      nodes:
        additionalProperties:
          additionalProperties: false
          properties:
            certificate:
              additionalProperties: false
              properties:
                secretKeyRef:
                  additionalProperties: false
                  properties:
                    name:
                      minLength: 1
                      type: string
                  required:
                  - name
            configuration:
              example: default
              type: string
          type: object
        type: object
      users:
        $ref: '#/components/schemas/User'
    required:
    - nodes
    - configurations
    type: object
title: Values
type: object

